import '../Models/coverage_area_model.dart';

List<CoverageArea> coverageAreaDataList = [
  CoverageArea(
      area: 'Sylhet - Zindabazar',
      district: 'Sylhet',
      zip: '3100',
      service: 'Sylhet Metro',
      cod: 0),
  CoverageArea(
      area: 'Sylhet - Amberkhana',
      district: 'Sylhet',
      zip: '3100',
      service: 'Sylhet Metro',
      cod: 0),
  CoverageArea(
      area: 'Sylhet - Kumarpara',
      district: 'Sylhet',
      zip: '3100',
      service: 'Sylhet Metro',
      cod: 0),
  CoverageArea(
      area: 'Sylhet - Lamabazar',
      district: 'Sylhet',
      zip: '3100',
      service: 'Sylhet Metro',
      cod: 0),
  CoverageArea(
      area: 'Sylhet - Shibganj',
      district: 'Sylhet',
      zip: '3100',
      service: 'Sylhet Metro',
      cod: 0),
  CoverageArea(
      area: 'Sylhet - Uposhohor',
      district: 'Sylhet',
      zip: '3100',
      service: 'Sylhet Metro',
      cod: 0),
  CoverageArea(
      area: 'Sylhet - Subhanighat',
      district: 'Sylhet',
      zip: '3100',
      service: 'Sylhet Metro',
      cod: 0),
  CoverageArea(
      area: 'Sylhet - Akhalia',
      district: 'Sylhet',
      zip: '3100',
      service: 'Sylhet Metro',
      cod: 0),
  CoverageArea(
      area: 'Sylhet - Srimangal',
      district: 'Sylhet',
      zip: '3210',
      service: 'Sylhet Outskirts',
      cod: 50),
  CoverageArea(
      area: 'Sylhet - Moulvibazar',
      district: 'Sylhet',
      zip: '3200',
      service: 'Sylhet Outskirts',
      cod: 50),
  CoverageArea(
      area: 'Sylhet - Sunamganj',
      district: 'Sylhet',
      zip: '3000',
      service: 'Sylhet Outskirts',
      cod: 50),
  CoverageArea(
      area: 'Sylhet - Habiganj',
      district: 'Sylhet',
      zip: '3300',
      service: 'Sylhet Outskirts',
      cod: 50),
  CoverageArea(
      area: 'Rajshahi - Shaheb Bazar',
      district: 'Rajshahi',
      zip: '6000',
      service: 'Rajshahi Metro',
      cod: 0),
  CoverageArea(
      area: 'Rajshahi - Laxmipur',
      district: 'Rajshahi',
      zip: '6000',
      service: 'Rajshahi Metro',
      cod: 0),
  CoverageArea(
      area: 'Rajshahi - Boalia',
      district: 'Rajshahi',
      zip: '6000',
      service: 'Rajshahi Metro',
      cod: 0),
  CoverageArea(
      area: 'Rajshahi - Motihar',
      district: 'Rajshahi',
      zip: '6000',
      service: 'Rajshahi Metro',
      cod: 0),
  CoverageArea(
      area: 'Rajshahi - Kazla',
      district: 'Rajshahi',
      zip: '6000',
      service: 'Rajshahi Metro',
      cod: 0),
  CoverageArea(
      area: 'Rajshahi - Rajpara',
      district: 'Rajshahi',
      zip: '6000',
      service: 'Rajshahi Metro',
      cod: 0),
  CoverageArea(
      area: 'Rajshahi - Shiroil',
      district: 'Rajshahi',
      zip: '6000',
      service: 'Rajshahi Metro',
      cod: 0),
  CoverageArea(
      area: 'Rajshahi - Puthia',
      district: 'Rajshahi',
      zip: '6200',
      service: 'Rajshahi Outskirts',
      cod: 50),
  CoverageArea(
      area: 'Rajshahi - Natore',
      district: 'Rajshahi',
      zip: '6400',
      service: 'Rajshahi Outskirts',
      cod: 50),
  CoverageArea(
      area: 'Rajshahi - Naogaon',
      district: 'Rajshahi',
      zip: '6500',
      service: 'Rajshahi Outskirts',
      cod: 50),
  CoverageArea(
      area: 'Rajshahi - Chapainawabganj',
      district: 'Rajshahi',
      zip: '6300',
      service: 'Rajshahi Outskirts',
      cod: 50),
  CoverageArea(
      area: 'Khulna - KDA Avenue',
      district: 'Khulna',
      zip: '9100',
      service: 'Khulna Metro',
      cod: 0),
  CoverageArea(
      area: 'Khulna - Boyra',
      district: 'Khulna',
      zip: '9100',
      service: 'Khulna Metro',
      cod: 0),
  CoverageArea(
      area: 'Khulna - Khalishpur',
      district: 'Khulna',
      zip: '9000',
      service: 'Khulna Metro',
      cod: 0),
  CoverageArea(
      area: 'Khulna - Daulatpur',
      district: 'Khulna',
      zip: '9000',
      service: 'Khulna Metro',
      cod: 0),
  CoverageArea(
      area: 'Khulna - Sonadanga',
      district: 'Khulna',
      zip: '9000',
      service: 'Khulna Metro',
      cod: 0),
  CoverageArea(
      area: 'Khulna - Rupsha',
      district: 'Khulna',
      zip: '9000',
      service: 'Khulna Metro',
      cod: 0),
  CoverageArea(
      area: 'Khulna - Shibbari',
      district: 'Khulna',
      zip: '9000',
      service: 'Khulna Metro',
      cod: 0),
  CoverageArea(
      area: 'Khulna - Nirala',
      district: 'Khulna',
      zip: '9000',
      service: 'Khulna Metro',
      cod: 0),
  CoverageArea(
      area: 'Khulna - Bagerhat',
      district: 'Khulna',
      zip: '9300',
      service: 'Khulna Outskirts',
      cod: 50),
  CoverageArea(
      area: 'Khulna - Satkhira',
      district: 'Khulna',
      zip: '9400',
      service: 'Khulna Outskirts',
      cod: 50),
  CoverageArea(
      area: 'Khulna - Jessore',
      district: 'Khulna',
      zip: '7400',
      service: 'Khulna Outskirts',
      cod: 50),
  CoverageArea(
      area: 'Barisal - Sadar Road',
      district: 'Barisal',
      zip: '8200',
      service: 'Barisal Metro',
      cod: 0),
  CoverageArea(
      area: 'Barisal - Natullabad',
      district: 'Barisal',
      zip: '8200',
      service: 'Barisal Metro',
      cod: 0),
  CoverageArea(
      area: 'Barisal - Rupatali',
      district: 'Barisal',
      zip: '8200',
      service: 'Barisal Metro',
      cod: 0),
  CoverageArea(
      area: 'Barisal - Kashipur',
      district: 'Barisal',
      zip: '8200',
      service: 'Barisal Metro',
      cod: 0),
  CoverageArea(
      area: 'Barisal - Chawkbazar',
      district: 'Barisal',
      zip: '8200',
      service: 'Barisal Metro',
      cod: 0),
  CoverageArea(
      area: 'Barisal - Banaripara',
      district: 'Barisal',
      zip: '8210',
      service: 'Barisal Outskirts',
      cod: 50),
  CoverageArea(
      area: 'Barisal - Pirojpur',
      district: 'Barisal',
      zip: '8500',
      service: 'Barisal Outskirts',
      cod: 50),
  CoverageArea(
      area: 'Barisal - Bhola',
      district: 'Barisal',
      zip: '8300',
      service: 'Barisal Outskirts',
      cod: 50),
  CoverageArea(
      area: 'Barisal - Patuakhali',
      district: 'Barisal',
      zip: '8600',
      service: 'Barisal Outskirts',
      cod: 50),
  CoverageArea(
      area: 'Rangpur - Station Road',
      district: 'Rangpur',
      zip: '5400',
      service: 'Rangpur Metro',
      cod: 0),
  CoverageArea(
      area: 'Dhanmondi - Rd 3',
      district: 'Dhaka',
      zip: '1209',
      service: 'Dhaka Metro',
      cod: 0),
  CoverageArea(
      area: 'Gulshan',
      district: 'Dhaka',
      zip: '1212',
      service: 'Dhaka Metro',
      cod: 0),
  CoverageArea(
      area: 'Mirpur - Rd 10',
      district: 'Dhaka',
      zip: '1216',
      service: 'Dhaka Metro',
      cod: 0),
  CoverageArea(
      area: 'Banani',
      district: 'Dhaka',
      zip: '1213',
      service: 'Dhaka Metro',
      cod: 0),
  CoverageArea(
      area: 'Mohammadpur',
      district: 'Dhaka',
      zip: '1207',
      service: 'Dhaka Metro',
      cod: 0),
  CoverageArea(
      area: 'Baridhara',
      district: 'Dhaka',
      zip: '1212',
      service: 'Dhaka Metro',
      cod: 0),
  CoverageArea(
      area: 'Uttara',
      district: 'Dhaka',
      zip: '1230',
      service: 'Dhaka Metro',
      cod: 0),
  CoverageArea(
      area: 'Motijheel',
      district: 'Dhaka',
      zip: '1000',
      service: 'Dhaka Metro',
      cod: 0),
  CoverageArea(
      area: 'Paltan',
      district: 'Dhaka',
      zip: '1000',
      service: 'Dhaka Metro',
      cod: 0),
  CoverageArea(
      area: 'Ramna',
      district: 'Dhaka',
      zip: '1000',
      service: 'Dhaka Metro',
      cod: 0),
  CoverageArea(
      area: 'Tejgaon',
      district: 'Dhaka',
      zip: '1215',
      service: 'Dhaka Metro',
      cod: 0),
  CoverageArea(
      area: 'Farmgate',
      district: 'Dhaka',
      zip: '1215',
      service: 'Dhaka Metro',
      cod: 0),
  CoverageArea(
      area: 'Shahbagh',
      district: 'Dhaka',
      zip: '1000',
      service: 'Dhaka Metro',
      cod: 0),
  CoverageArea(
      area: 'New Market',
      district: 'Dhaka',
      zip: '1205',
      service: 'Dhaka Metro',
      cod: 0),
  CoverageArea(
      area: 'Dhanmondi - Rd 27',
      district: 'Dhaka',
      zip: '1209',
      service: 'Dhaka Metro',
      cod: 0),
  CoverageArea(
      area: 'Dhanmondi - Rd 15',
      district: 'Dhaka',
      zip: '1209',
      service: 'Dhaka Metro',
      cod: 0),
  CoverageArea(
      area: 'Dhanmondi - Rd 7',
      district: 'Dhaka',
      zip: '1205',
      service: 'Dhaka Metro',
      cod: 0),
  CoverageArea(
      area: 'Gulshan - Rd 79',
      district: 'Dhaka',
      zip: '1212',
      service: 'Dhaka Metro',
      cod: 0),
  CoverageArea(
      area: 'Gulshan - Rd 35',
      district: 'Dhaka',
      zip: '1212',
      service: 'Dhaka Metro',
      cod: 0),
  CoverageArea(
      area: 'Gulshan - Rd 11',
      district: 'Dhaka',
      zip: '1212',
      service: 'Dhaka Metro',
      cod: 0),
  CoverageArea(
      area: 'Bashundhara',
      district: 'Dhaka',
      zip: '1229',
      service: 'Dhaka Metro',
      cod: 0),
  CoverageArea(
      area: 'Badda',
      district: 'Dhaka',
      zip: '1212',
      service: 'Dhaka Metro',
      cod: 0),
  CoverageArea(
      area: 'Rampura',
      district: 'Dhaka',
      zip: '1219',
      service: 'Dhaka Metro',
      cod: 0),
  CoverageArea(
      area: 'Malibagh',
      district: 'Dhaka',
      zip: '1217',
      service: 'Dhaka Metro',
      cod: 0),
  CoverageArea(
      area: 'Moghbazar',
      district: 'Dhaka',
      zip: '1217',
      service: 'Dhaka Metro',
      cod: 0),
  CoverageArea(
      area: 'Shantinagar',
      district: 'Dhaka',
      zip: '1217',
      service: 'Dhaka Metro',
      cod: 0),
  CoverageArea(
      area: 'Khilgaon',
      district: 'Dhaka',
      zip: '1219',
      service: 'Dhaka Metro',
      cod: 0),
  CoverageArea(
      area: 'Basabo',
      district: 'Dhaka',
      zip: '1214',
      service: 'Dhaka Metro',
      cod: 0),
  CoverageArea(
      area: 'Savar',
      district: 'Dhaka',
      zip: '1340',
      service: 'Dhaka Outskirts',
      cod: 50),
  CoverageArea(
      area: 'Ashulia',
      district: 'Dhaka',
      zip: '1341',
      service: 'Dhaka Outskirts',
      cod: 50),
  CoverageArea(
      area: 'Gazipur',
      district: 'Dhaka',
      zip: '1700',
      service: 'Dhaka Outskirts',
      cod: 50),
  CoverageArea(
      area: 'Tongi',
      district: 'Dhaka',
      zip: '1710',
      service: 'Dhaka Outskirts',
      cod: 50),
  CoverageArea(
      area: 'Narayanganj',
      district: 'Dhaka',
      zip: '1400',
      service: 'Dhaka Outskirts',
      cod: 50),
  CoverageArea(
      area: 'Keraniganj',
      district: 'Dhaka',
      zip: '1310',
      service: 'Dhaka Outskirts',
      cod: 50),
  CoverageArea(
      area: 'Demra',
      district: 'Dhaka',
      zip: '1360',
      service: 'Dhaka Outskirts',
      cod: 50),
  CoverageArea(
      area: 'Jatrabari',
      district: 'Dhaka',
      zip: '1362',
      service: 'Dhaka Outskirts',
      cod: 50),
  CoverageArea(
      area: 'Kamrangirchar',
      district: 'Dhaka',
      zip: '1211',
      service: 'Dhaka Outskirts',
      cod: 50),
  CoverageArea(
      area: 'Lalbagh',
      district: 'Dhaka',
      zip: '1211',
      service: 'Dhaka Metro',
      cod: 0),
  CoverageArea(
      area: 'Azimpur',
      district: 'Dhaka',
      zip: '1205',
      service: 'Dhaka Metro',
      cod: 0),
  CoverageArea(
      area: 'Elephant Road',
      district: 'Dhaka',
      zip: '1205',
      service: 'Dhaka Metro',
      cod: 0),
  CoverageArea(
      area: 'Green Road',
      district: 'Dhaka',
      zip: '1205',
      service: 'Dhaka Metro',
      cod: 0),
  CoverageArea(
      area: 'Panthapath',
      district: 'Dhaka',
      zip: '1215',
      service: 'Dhaka Metro',
      cod: 0),
  CoverageArea(
      area: 'Mohakhali',
      district: 'Dhaka',
      zip: '1212',
      service: 'Dhaka Metro',
      cod: 0),
  CoverageArea(
      area: 'Banani DOHS',
      district: 'Dhaka',
      zip: '1206',
      service: 'Dhaka Metro',
      cod: 0),
  CoverageArea(
      area: 'Baridhara DOHS',
      district: 'Dhaka',
      zip: '1206',
      service: 'Dhaka Metro',
      cod: 0),
  CoverageArea(
      area: 'Mohammadpur DOHS',
      district: 'Dhaka',
      zip: '1207',
      service: 'Dhaka Metro',
      cod: 0),
  CoverageArea(
      area: 'Mirpur DOHS',
      district: 'Dhaka',
      zip: '1216',
      service: 'Dhaka Metro',
      cod: 0),
  CoverageArea(
      area: 'Banani - Rd 11',
      district: 'Dhaka',
      zip: '1213',
      service: 'Dhaka Metro',
      cod: 0),
  CoverageArea(
      area: 'Banani - Rd 13',
      district: 'Dhaka',
      zip: '1213',
      service: 'Dhaka Metro',
      cod: 0),
  CoverageArea(
      area: 'Banani - Rd 15',
      district: 'Dhaka',
      zip: '1213',
      service: 'Dhaka Metro',
      cod: 0),
  CoverageArea(
      area: 'Baridhara - Rd 1',
      district: 'Dhaka',
      zip: '1212',
      service: 'Dhaka Metro',
      cod: 0),
  CoverageArea(
      area: 'Baridhara - Rd 3',
      district: 'Dhaka',
      zip: '1212',
      service: 'Dhaka Metro',
      cod: 0),
  CoverageArea(
      area: 'Baridhara - Rd 5',
      district: 'Dhaka',
      zip: '1212',
      service: 'Dhaka Metro',
      cod: 0),
  CoverageArea(
      area: 'Uttara - Rd 1',
      district: 'Dhaka',
      zip: '1230',
      service: 'Dhaka Metro',
      cod: 0),
  CoverageArea(
      area: 'Uttara - Rd 3',
      district: 'Dhaka',
      zip: '1230',
      service: 'Dhaka Metro',
      cod: 0),
  CoverageArea(
      area: 'Uttara - Rd 5',
      district: 'Dhaka',
      zip: '1230',
      service: 'Dhaka Metro',
      cod: 0),
  CoverageArea(
      area: 'Mirpur - Rd 1',
      district: 'Dhaka',
      zip: '1216',
      service: 'Dhaka Metro',
      cod: 0),
// Add more Data objects here as needed
];
