
import '../Models/payment_model.dart';

List<Payment> payments = [
  Payment(paymentNo: "MPY-00001", status: "Delivery Payment Accept", totalParcel: "1", rcvParcel: "1", amt: "409", rcvAmt: "409",date: DateTime.now().toString()),
Payment(paymentNo: "MPY-00002", status: "Delivery Payment Accept", totalParcel: "2", rcvParcel: "2", amt: "819", rcvAmt: "819", date: DateTime.now().toString()),
Payment(paymentNo: "MPY-00003", status: "Delivery Payment Reject", totalParcel: "1", rcvParcel: "0", amt: "205", rcvAmt: "0", date: DateTime.now().toString()),
Payment(paymentNo: "MPY-00004", status: "Delivery Payment Partial", totalParcel: "3", rcvParcel: "2", amt: "1227", rcvAmt: "818", date: DateTime.now().toString()),
Payment(paymentNo: "MPY-00005", status: "Delivery Payment Accept", totalParcel: "4", rcvParcel: "4", amt: "1636", rcvAmt: "1636", date: DateTime.now().toString()),
Payment(paymentNo: "MPY-00006", status: "Delivery Payment Reject", totalParcel: "2", rcvParcel: "0", amt: "410", rcvAmt: "0", date: DateTime.now().toString()),
Payment(paymentNo: "MPY-00007", status: "Delivery Payment Partial", totalParcel: "5", rcvParcel: "3", amt: "2045", rcvAmt: "1227", date: DateTime.now().toString()),
Payment(paymentNo: "MPY-00008", status: "Delivery Payment Accept", totalParcel: "6", rcvParcel: "6", amt: "2454", rcvAmt: "2454", date: DateTime.now().toString()),
Payment(paymentNo: "MPY-00009", status: "Delivery Payment Reject", totalParcel: "3", rcvParcel: "0", amt: "615", rcvAmt: "0", date: DateTime.now().toString()),
Payment(paymentNo: "MPY-00010", status: "Delivery Payment Partial", totalParcel: "7", rcvParcel: "4", amt: "2863", rcvAmt: "1636", date: DateTime.now().toString()),
Payment(paymentNo: "MPY-00011", status: "Delivery Payment Accept", totalParcel: "8", rcvParcel: "8", amt: "3272", rcvAmt: "3272", date: DateTime.now().toString()),
Payment(paymentNo: "MPY-00012", status: "Delivery Payment Reject", totalParcel: "4", rcvParcel: "0", amt: "820", rcvAmt: "0", date: DateTime.now().toString()),
Payment(paymentNo: "MPY-00013", status: "Delivery Payment Partial", totalParcel: "9", rcvParcel: "5", amt: "3681", rcvAmt: "2045", date: DateTime.now().toString()),
Payment(paymentNo: "MPY-00014", status: "Delivery Payment Accept", totalParcel: "10", rcvParcel: "10", amt: "4090", rcvAmt: "4090", date: DateTime.now().toString()),
Payment(paymentNo: "MPY-00015", status: "Delivery Payment Reject", totalParcel: "5", rcvParcel: "0", amt: "1025", rcvAmt: "0", date: DateTime.now().toString()),
Payment(paymentNo: "MPY-00016", status: "Delivery Payment Partial", totalParcel: "11", rcvParcel: "6", amt: "4499", rcvAmt: "2454", date: DateTime.now().toString()),
Payment(paymentNo: "MPY-00017", status: "Delivery Payment Accept", totalParcel: "12", rcvParcel: "12", amt: "4908", rcvAmt: "4908", date: DateTime.now().toString()),
Payment(paymentNo: "MPY-00018", status: "Delivery Payment Reject", totalParcel: "6", rcvParcel: "0", amt: "1230", rcvAmt: "0", date: DateTime.now().toString()),
Payment(paymentNo: "MPY-00019", status: "Delivery Payment Partial", totalParcel: "13", rcvParcel: "7", amt: "5317", rcvAmt: "2863", date: DateTime.now().toString()),
Payment(paymentNo: "MPY-00020", status: "Delivery Payment Accept", totalParcel: "14", rcvParcel: "14", amt: "5726", rcvAmt: "5726", date: DateTime.now().toString()),
Payment(paymentNo: "MPY-00021", status: "Delivery Payment Reject", totalParcel: "7", rcvParcel: "0", amt: "1435", rcvAmt: "0", date: DateTime.now().toString()),
Payment(paymentNo: "MPY-00022", status: "Delivery Payment Partial", totalParcel: "15", rcvParcel: "8", amt: "6135", rcvAmt: "3272", date: DateTime.now().toString()),
Payment(paymentNo: "MPY-00023", status: "Delivery Payment Accept", totalParcel: "16", rcvParcel: "16", amt: "6544", rcvAmt: "6544", date: DateTime.now().toString()),
Payment(paymentNo: "MPY-00024", status: "Delivery Payment Reject", totalParcel: "8", rcvParcel: "0", amt: "1640", rcvAmt: "0", date: DateTime.now().toString()),
Payment(paymentNo: "MPY-00025", status: "Delivery Payment Partial", totalParcel: "17", rcvParcel: "9", amt: "6953", rcvAmt: "3681", date: DateTime.now().toString()),
Payment(paymentNo: "MPY-00026", status: "Delivery Payment Accept", totalParcel: "18", rcvParcel: "18", amt: "7362", rcvAmt: "7362", date: DateTime.now().toString()),
Payment(paymentNo: "MPY-00027", status: "Delivery Payment Reject", totalParcel: "9", rcvParcel: "0", amt: "1845", rcvAmt: "0", date: DateTime.now().toString()),
Payment(paymentNo: "MPY-00028", status: "Delivery Payment Partial", totalParcel: "19", rcvParcel: "10", amt: "7771", rcvAmt: "4090", date: DateTime.now().toString()),
Payment(paymentNo: "MPY-00029", status: "Delivery Payment Accept", totalParcel: "20", rcvParcel: "20", amt: "8180", rcvAmt: "8180", date: DateTime.now().toString()),
];