
import 'package:st_courier/Models/payment_request_model.dart';

final List<PaymentRequest> paymentRequests =  [
  PaymentRequest(paymentNo: 'Payment-00001', status: 'Pending', note: 'null', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00002', status: 'Rejected', note: 'Insufficient funds', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00003', status: 'Accepted', note: 'null', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00005', status: 'Pending', note: 'null', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00006', status: 'Rejected', note: 'Invalid card number', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00007', status: 'Accepted', note: 'null', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00008', status: 'Pending', note: 'null', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00009', status: 'Rejected', note: 'Expired card', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00010', status: 'Accepted', note: 'null', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00011', status: 'Pending', note: 'null', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00012', status: 'Rejected', note: 'Incorrect CVV', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00013', status: 'Accepted', note: 'null', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00014', status: 'Pending', note: 'null', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00015', status: 'Rejected', note: 'Transaction limit exceeded', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00016', status: 'Accepted', note: 'null', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00017', status: 'Pending', note: 'null', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00018', status: 'Rejected', note: 'Card blocked', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00019', status: 'Accepted', note: 'null', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00020', status: 'Pending', note: 'null', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00021', status: 'Rejected', note: 'Network error', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00022', status: 'Accepted', note: 'null', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00023', status: 'Pending', note: 'null', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00024', status: 'Rejected', note: 'Server error', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00025', status: 'Accepted', note: 'null', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00026', status: 'Pending', note: 'null', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00027', status: 'Rejected', note: 'Invalid currency', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00028', status: 'Accepted', note: 'null', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00029', status: 'Pending', note: 'null', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00030', status: 'Rejected', note: 'Payment method not supported', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00031', status: 'Accepted', note: 'null', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00032', status: 'Pending', note: 'null', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00033', status: 'Rejected', note: 'Duplicate payment', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00034', status: 'Accepted', note: 'null', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00035', status: 'Pending', note: 'null', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00036', status: 'Rejected', note: 'Fraudulent transaction', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00037', status: 'Accepted', note: 'null', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00038', status: 'Pending', note: 'null', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00039', status: 'Rejected', note: 'Customer dispute', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00040', status: 'Accepted', note: 'null', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00041', status: 'Pending', note: 'null', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00042', status: 'Rejected', note: 'Refund request', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00043', status: 'Accepted', note: 'null', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00044', status: 'Pending', note: 'null', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00045', status: 'Rejected', note: 'Chargeback request', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00046', status: 'Accepted', note: 'null', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00047', status: 'Pending', note: 'null', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00048', status: 'Rejected', note: 'Tax issue', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00049', status: 'Accepted', note: 'null', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00050', status: 'Pending', note: 'null', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00051', status: 'Rejected', note: 'Currency conversion error', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00052', status: 'Accepted', note: 'null', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00053', status: 'Pending', note: 'null', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00054', status: 'Rejected', note: 'Payment gateway error', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00055', status: 'Accepted', note: 'null', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00056', status: 'Pending', note: 'null', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00057', status: 'Rejected', note: 'Payment processor error', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00058', status: 'Accepted', note: 'null', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00059', status: 'Pending', note: 'null', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00060', status: 'Rejected', note: 'Payment service provider error', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00061', status: 'Accepted', note: 'null', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00062', status: 'Pending', note: 'null', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00063', status: 'Rejected', note: 'Payment verification error', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00064', status: 'Accepted', note: 'null', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00065', status: 'Pending', note: 'null', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00066', status: 'Rejected', note: 'Payment confirmation error', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00067', status: 'Accepted', note: 'null', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00068', status: 'Pending', note: 'null', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00069', status: 'Rejected', note: 'Payment cancellation error', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00070', status: 'Accepted', note: 'null', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00071', status: 'Pending', note: 'null', date: DateTime.now().toString()),
  PaymentRequest(paymentNo: 'Payment-00072', status: 'Accepted', note: 'null', date: DateTime.now().toString()),
];